# Generated by Django 6.0.8 on 2026-08-13 21:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysale',
            name='meat_sales_amount',
        ),
        migrations.AddField(
            model_name='dailysale',
            name='total_food_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='dailysale',
            name='total_meat_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='total_money_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='foodsalerecord',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pigs.fooditem'),
        ),
    ]
