# Generated by Django 6.0.8 on 2026-08-13 21:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0002_remove_dailysale_meat_sales_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProfitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_pigs', models.PositiveIntegerField(default=0)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_meat_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('finalized_date', models.DateField()),
                ('slaughter_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_report', to='pigs.slaughterbatch')),
            ],
            options={
                'ordering': ['-finalized_date', '-created_at'],
            },
        ),
    ]
