# Generated by Django 6.0.8 on 2026-08-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0003_batchprofitreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigsalerecord',
            name='meat_weight_sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
