# Generated by Django 6.0.8 on 2026-08-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0006_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='slaughter_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='pigs.slaughterbatch'),
        ),
    ]
