# Generated by Django 6.0.8 on 2026-08-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0007_dailysale_slaughter_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysale',
            old_name='total_meat_weight_kg',
            new_name='meat_price_per_kg',
        ),
    ]
