# Generated by Django 6.0.8 on 2026-08-17 17:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0008_rename_total_meat_weight_kg_dailysale_meat_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='total_meat_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
