# Generated by Django 6.0.8 on 2026-08-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0009_dailysale_total_meat_weight_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-created_at'], 'permissions': [('manage_data_management', 'Can manage data management')]},
        ),
    ]
