# Generated by Django 6.0.8 on 2026-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0010_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Hajachinjwa'), ('SLAUGHTERED', 'Amechinjwa'), ('FINISHED', 'Nyama imeisha')], default='AVAILABLE', max_length=20),
        ),
    ]
